serviceInstance:
  nameOverride: lesson-service
  image:
    repository: tyku/czech_lang
    imagePullPolicy: Always
    tag: latest
  containerPort: 8000
  service:
    type: ClusterIP
    port: 80
postgresql:
  enabled: false